#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            caches:
              - maven
            script:
              - mvn -B verify --file pom.xml
            after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
              - pipe: atlassian/checkstyle-report:0.3.0
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.5.1

  branches:
    master:
      - step:
          name: Package
          caches:
            - maven
          script:
            - sed -i "s/%versionNumber%/1.${BITBUCKET_BUILD_NUMBER}-SNAPSHOT/g" pom.xml
            - mvn package
            - pipe: atlassian/bitbucket-upload-file:0.3.2
              variables:
                BITBUCKET_USERNAME: $BITBUCKET_USERNAME
                BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
                FILENAME: "target/Essentials-1.${BITBUCKET_BUILD_NUMBER}-SNAPSHOT.jar"