hello-msg: "&5Üdv &3%player% &5!"
hello-submsg: "&2Szerveren épp &4%daytime% &2van"

permission-msg: "You dont have permission!"
player-not-found-msg: "Player not found!"

use-db: true
db:
  host: 192.168.2.55
  port: 3306
  db: Essentials_plugin
  user: admin
  pw: Gaborka11