name: Essentials
version: ${project.version}
main: me.agronaut.essentials.Essentials
api-version: 1.13

commands:
  tp:
    usage: /tp [playerName]
    description: Teleport to other player
  tph:
    usage: /tph [playerName]
    description: Teleport other player to you
  fly:
    usage: /fly
    description: Toggle fly on/off
  heal:
    usage: /heal [playerName]
    description: Heal yourself or other player
  feed:
    usage: /feed [playerName]
    description: Feed yourself or other player
  hide:
    usage: /hide
    description: Toggle invisibility on/off
  inventory:
    usage: /inventory [playerName]
    description: open other players inventory
    aliases:
      - inv
      - i
  scoreboard:
    usage: /scoreboard
    description: toggle scoreboard on/off
    aliases: [sb]
  permissions:
    usage: /permissions <add | remove | list> <player> [permission]
    description: add or remove or list user permissions
    aliases: [pm]
  permissions-group:
    usage: /permissions-group <add | addto | remove | removefrom | list> <group> [permission | player]
    description: add or remove or list group permissions
    aliases: [pmg]
  money:
    usage: /money [player]
    description: show your money or given player's money