version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:16.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - store_artifacts:
          path: /home/circleci/project/target/Essentials-1.0-SNAPSHOT.jar
          destination: Essetials.jar
  test:
    docker:
      - image: cimg/openjdk:16.0
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test

workflows:
  Build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
